### ISSUE TITLE
Support for https links

### ISSUE THREAD

**Issue by gjimenezf** [Dontwait00/nXDownload#1]
Does your app support https links?

**Comment by 0d3n3h547v** [comment]
Unfortunatly, no.

Bigger answer:
The HTTPS protocol is a massive library containing SSL encryption, Checksum, MD5, etc.. meaning that needs to be ported to the switch, And im not going to :)

This doesnt mean that HTTP protocol is obsolete around the internet. There are still a lot of websites that doesnt encrypt the traffic, i.e. Mediafire, 1fichier, and probably many others

I just founded that few websites doesnt work (meaning requires HTTPS library):

- Mega
- Google Drive
- More websites i need to test...

**Comment by gjimenezf** [comment]
But if you compile libcurl with https support?
Libcurl source code already support it

**Comment by 0d3n3h547v** [comment]
Sorry for late answer, but i was taking a break from everything except Life™

`switch-libcurl` and `switch-openssl` are corrently disconnected together from ufficial Devkitpro dependencies (because they are conflicting to unfinished work/unstable dependencies)

You can already have a look on current work of `switch-openssl` from "unofficial" [Devkitpro repository](https://github.com/devkitPro/newlib/issues/8) issues.

We just need time & effort from developers like @WinterMute and/or others to get the time and finish it.

**Comment by SegFault42** [comment]
@gjimenezf Https supported now. 

We will release soon.

Enjoy !
